### ISSUE TITLE
Running geocode in test returns [0.0, 0.0]

### ISSUE THREAD

**Issue by michaeljkchoi** [alexreisner/geocoder#1095]
It looks like when we try to run `@address.geocode` directly in a test, it returns [0.0, 0.0].

For example,

```
# test/models/address_test.rb
test "geocode method" do
  address = addresses(:toronto)
  assert_not_equals [0.0, 0.0], address.geocode # FAILS
end
```

but if we use it in a callback, then it seems to be saving the correct latitude and longitude values.

I have the following stub

```
# test/test_helper.rb
Geocoder::Lookup::Test.add_stub(
  "1 Toronto Street, Toronto, ON, Canada", [{
    latitude: 43.7084885,
    longitude: -79.3959108
  }]
)
```

**Comment by alexreisner** [comment]
What's the value of `addresses(:toronto)`?

**Comment by michaeljkchoi** [comment]
```
toronto:
  street_number: 89
  line1: Roehampton Avenue
  city: Toronto
  subregion: "ON"
  country: Canada
  postal_code: M4P 1P9
  latitude: 43.7084885
  longitude: -79.3980995
```
