### ISSUE TITLE
Testing near scope with Geocoder::Lookup::Test doesn't seem to work

### ISSUE THREAD

**Issue by gaetanm** [alexreisner/geocoder#1181]
I have a simple feature test with RSpec:
```ruby
fill_in 'user_address', with: '160-0021, Japan'
click_on 'Find food'

expect(page).to have_content('Mos Burger')
expect(page).to have_content('Krispy Kreme Doughnuts')
expect(page).to_not have_content('Minamoto Sushi')
```

The spec works as expected till I start to use `Geocoder::Lookup::Test`:
```ruby
before(:all) do
    Geocoder.configure(:lookup => :test)

    Geocoder::Lookup::Test.set_default_stub([{ latitude:  35.6960834,
                                               longitude: 139.7026251,
                                               address: '160-0021, Japan',
                                               state: 'Tokyo',
                                               city: 'Shinjuku',
                                               state_code: 'Tokyo',
                                               postal_code: '160-0021',
                                               country: 'Japan',
                                               country_code: 'JP' }])
  end
```

When I check RSpec log, it seems that no value were found about the given address:
```sql
SELECT restaurants.*, 6371.0 * 2 * ASIN(SQRT(POWER(SIN((0.0 - restaurants.latitude)...
```

I tried to dig into the gem a bit but I still can't figure why I have this trouble.

**Comment by TrangPham** [comment]
Hi @gaetanm

I think this is because the `.near` function is calling into your SQL database while the Lookup::Test does not actually mock out the results in SQL. What the `.near` function does is to look at the stored results that you have for a certain ActiveRecord and search for instances of that model that are `.near` the coordinates you pass in. 

To test the `.near` functionality you'd have to set up some test fixtures for your model. We used to use this repo called `geocoder_test` to test our SQL / Model based functionality. You can use it to see how to set up your test case. See fixture: https://github.com/alexreisner/geocoder_test/tree/master/base/test/fixtures/venues.yml and test cases: https://github.com/alexreisner/geocoder_test/blob/master/base/test/unit/active_record_test.rb#L97
And you'll need to load your test fixtures similar to: https://github.com/alexreisner/geocoder_test/blob/master/rails30/test/test_helper.rb#L10

I believe that if you wanted to use the Lookup::Test for testing `.near` you'd have to add a bunch of stubs, make sure that in your code path of the test case that your model is getting geocoded such that in your model values of the test stub are saved, and then you can call `.near` on your model. I'm not 100% sure this would work though. 

Hope that helps you out! 
Thanks,
Thu Trang Pham

**Comment by gaetanm** [comment]
Hi @TrangPham, thanks for your help.

Actually I'm already using fixtures for my tests, like:
```yml
mos_burger:
  name: 'Mos Burger'
  address: '160-0023, Japan'
  latitude: 35.6913457
  longitude: 139.69369
  city: 'Shinjuku'
  country: 'Japan'
  country_code: 'JP'
  postal_code: '160-0023'
  state: 'Tokyo'
  state_code: 'Tokyo'

krispy_kreme_doughnuts:
  name: 'Krispy Kreme Doughnuts'
  address: '160-0021, Japan'
  latitude: 35.6960834
  longitude: 139.7026251
  city: 'Shinjuku'
  country: 'Japan'
  country_code: 'JP'
  postal_code: '160-0021'
  state: 'Tokyo'
  state_code: 'Tokyo'
```

And they are all correctly loaded, no doubt about that:
```ruby
RSpec.feature 'User searches restaurants', type: :feature do
  fixtures :restaurants
```

> I believe that if you wanted to use the Lookup::Test for testing .near you'd have to add a bunch of stubs

What do you call `stubs`? Like `obj.stub(:message)`?

By the way, I forgot to say that the feature I'm testing works as expected if I don't configure Geocoder in test mode.
